### ISSUE TITLE
视频不输出地址了啊

### ISSUE THREAD

**Issue by ivkeji** [xinpianchang/nsplayer#4]

**Comment by ivkeji** [comment]
https://www.xinpianchang.com/a11801512?from=articlePageOther
https://ks-xpc5.xpccdn.com/369beb81-d609-44f8-804b-a1af05ac1606.mp4

**Comment by tangye1234** [comment]
> https://www.xinpianchang.com/a11801512?from=articlePageOther https://ks-xpc5.xpccdn.com/369beb81-d609-44f8-804b-a1af05ac1606.mp4

**Comment by tangye1234** [comment]
这个问题与 nsplayer 无关，nsplayer 只是一个通用的播放器，新片场播放器只是使用了这个播放器的源码进行开发，你问的问题，我无法解答
